---
- name: Install go packages
  pkgng:
    name:
      - go120
    state: present
  tags: ['pkg', 'golang']

- name: Create go symlink
  file:
    src: go120
    dest: /usr/local/bin/go
    state: link
  tags: ['golang']

- name: Create gofmt symlink
  file:
    src: gofmt120
    dest: /usr/local/bin/gofmt
    state: link
  tags: ['golang']
