---
- name: Install go packages
  pkgng:
    name:
      - go121
    state: present

- name: Create go symlink
  file:
    src: go121
    dest: /usr/local/bin/go
    state: link

- name: Create gofmt symlink
  file:
    src: gofmt121
    dest: /usr/local/bin/gofmt
    state: link
