---
- name: Install required packages
  pkgng:
    name:
      - bash
      - bash-completion
      - curl
      - coreutils
      - diffutils
      - findutils
      - gawk
      - git
      - gmake
      - gnugrep
      - gnuls
      - gnupg
      - gsed
      - gtar
      - mc
      - nmap
      - psmisc
      - python3
      - python311
      - rsync
      - screen
      - tmux
      - util-linux
      - vim
      - wget
    state: present

- name: Add dports collection
  shell: git clone --depth 1 https://github.com/DragonFlyBSD/DPorts /usr/ports
  args:
    creates: /usr/ports

#- name: Add dports collection
#  git:
#    repo: https://github.com/DragonFlyBSD/DPorts
#    dest: /usr/dports
#    depth: 1
