---
- name: Add src collection
  shell: git clone --depth 1 --branch DragonFly_RELEASE_6_4 https://github.com/DragonFlyBSD/DragonFlyBSD /usr/src
  args:
    creates: /usr/src
  tags: ['src']

- name: Copy /etc/make.conf
  copy:
    src: make.conf
    dest: /etc/make.conf
    owner: root
    group: wheel
    mode: 0644
  tags: ['src']

- name: Copy CUSTOM kernel configuration
  copy:
    src: CUSTOM
    dest: /usr/src/sys/config/CUSTOM
    mode: 0644
  tags: ['src']
