---
#- name: Add src collection
#  git:
#    repo: git://git.dragonflybsd.org/dragonfly.git
#    dest: /usr/src
#    depth: 1
#    version: DragonFly_RELEASE_6_4
#  tags: ['src']

- name: Copy /etc/make.conf
  copy:
    src: make.conf
    dest: /etc/make.conf
    owner: root
    group: wheel
    mode: 0644

- name: Copy CUSTOM kernel configuration
  copy:
    src: CUSTOM
    dest: /usr/src/sys/config/CUSTOM
#    owner: root
#    group: wheel
    mode: 0644
