---
- name: Add user to needed groups
  user:
    name: ricardo
    groups: wheel,operator
    append: yes
    shell: /usr/local/bin/bash
  tags: ['user']

- name: Fix HOME permissions
  file:
    path: /home/ricardo
    state: directory
    owner: ricardo
    group: ricardo
    mode: '0750'
  tags: ['user']
